---
# tasks file for ansible-arch-bluetooth-keyboard

- name: Install required packages
  become: yes
  pacman: 
    name={{ item }} 
    state=latest
  loop: [ 'bluez', 'bluez-utils' ]


  # AutoEnable defines option to enable all controllers when they are found.
- name: bluetooth AutoEnable=true
  become: yes
  lineinfile:
    dest: /etc/bluetooth/main.conf
    regexp: '#?AutoEnable='
    line: 'AutoEnable=true'